pes = float(input(" Digite um numero em pés"))
pol = (pes * 12)
jardas = (pes / 3)
milhas = (pes / 5280)
print("a conversão de pés para polegadas é: " , pol)
print("a conversão de pés para jardas é: " , jardas)
print("a conversão de pés para milhas é: " , milhas)
